[project]
name = "permuto2nerfstudio"
version = "0.1.0"

dependencies=[
    "nerfstudio>=0.3.0"
]

[tool.setuptools.packages.find]
include = ["permuto*"]

[project.entry-points.'nerfstudio.method_configs']
permutosdf = 'permuto2nerfstudio.permuto_config:permuto_sdf_method'
